title = "Ron Forbes"
baseURL = "https://ronforbes.me"
tags = ["resume", "portfolio"]
languageCode = "en-US"
config = "config.toml"
theme = "osprey"
canonifyURLS = true
googleAnalytics = "UA-66544558-1"
disqusShortname = "ronforbes"
disableKinds = ["taxonomy", "taxonomyTerm"] # This theme does not currently use "tag" and "category" taxonomies

[Params]
    tagline = "Product Manager | Game Developer | Entrepreneur"
    author = "Ron Forbes"
    description = "Product manager, game developer and entrepreneur living in Venice, CA."
    logoBig = "/images/RonOmegaForbesLogo.png"
    logoSmall = "/images/RonOmegaForbesLogo.png"
    favicon = "favicon.ico"
    opengraphImage = "/images/RonOmegaForbesLogo.png"
    twitter = "ronforbes"
    linkedin = "ronforbes"
    github = "ronforbes"
    facebook = "ronaldomegaforbesjr"
    email = "r@ronforbes.me"
    googleTagManager = ""
    highlightJS = true
    copyright = true
    credit = false
    customCSS = false
    cacheBustCSS = false
    cacheBustJS = false
    ajaxFormspree = true

[[menu.main]]
    name = "About"
    url  = "/#about"
    weight = 1
[[menu.main]]
    name = "Work"
    url  = "/#work"
    weight = 2
[[menu.main]]
    name = "Blog"
    url  = "/#blog"
    weight = 3
[[menu.main]]
    name = "Contact"
    url  = "/#contact"
    weight = 4